version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: bio_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bio_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend_ai
      dockerfile: Dockerfile.backend
    container_name: bio_fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./backend_ai:/app
    environment:
      - DATABASE_URL=postgresql://admin:password@db:5432/bio_db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: bio_nextjs
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data: